version: '3.5'
services: 
    web:
      image: aoliveiraa/nginx:1.0
      ports: 
          - "80:80"
      restart: always
      volumes: 
          - ./wiki/:/var/www/html
      depends_on: 
          - php-wiki
          - mysql
      networks: 
         - php-wiki
        
#PHP-FPM7
    php-wiki:
      image: aoliveiraa/php:1.0
      ports: 
        - "9000:9000" 
      restart: always
      volumes: 
          - ./wiki/:/var/www/html
      depends_on: 
          - mysql
      networks: 
        - php-wiki
      
    
#BANCO-MYSQL  

    mysql:
      image: aoliveiraa/mariadb:1.0
      environment:  
          MYSQL_ROOT_PASSWORD: wiki
          MYSQL_DATABASE: wiki
          MYSQL_USER: wiki
          MYSQL_PASSWORD: wiki

      ports:  
        - "3306:3306"  
      restart: always
      volumes: 
          -  ..//mariadb/data/mysql/:/var/lib/mysql/
      networks: 
        - php-wiki
        
     
networks: 
  php-wiki:
    driver: bridge
